version: '3'
services:
  # my-app:
  #   image: 656985594497.dkr.ecr.us-east-2.amazonaws.com/my-app:1.6
  #   ports:
  #     - 3000:3000
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    depends_on:
      - "mongodb"
    command: /bin/bash -c "sleep 5; nc -vz mongodb 27017; cd ../mongo-express && node app.js" 
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
